/*
 * Copyright (C) 2017, Vincenzo Bove <vincenzo.bove@prodrive-technologies.com>
 *
 * SPDX-License-Identifier:	GPL-2.0+
 */

#ifndef __FSP_CONFIGS_H__
#define __FSP_CONFIGS_H__

#ifndef __ASSEMBLY__
struct fsp_config_data {
	struct fsp_cfg_common	common;
	struct upd_region	fsp_upd;
};

struct fspinit_rtbuf {
	struct common_buf	common;	/* FSP common runtime data structure */
};
#endif

/* FSP user configuration settings */

#define PAM0_HIENABLE_RW_DMI_ONLY				0
#define PAM0_HIENABLE_R_DRAM_W_DMI				1
#define PAM0_HIENABLE_R_DMI_W_DRAM				2
#define PAM0_HIENABLE_RW_DRAM_ONLY				3

#define PAM1_LOENABLE_RW_DMI_ONLY				0
#define PAM1_LOENABLE_R_DRAM_W_DMI				1
#define PAM1_LOENABLE_R_DMI_W_DRAM				2
#define PAM1_LOENABLE_RW_DRAM_ONLY				3

#define PAM1_HIENABLE_RW_DMI_ONLY				0
#define PAM1_HIENABLE_R_DRAM_W_DMI				1
#define PAM1_HIENABLE_R_DMI_W_DRAM				2
#define PAM1_HIENABLE_RW_DRAM_ONLY				3

#define PAM2_LOENABLE_RW_DMI_ONLY				0
#define PAM2_LOENABLE_R_DRAM_W_DMI				1
#define PAM2_LOENABLE_R_DMI_W_DRAM				2
#define PAM2_LOENABLE_RW_DRAM_ONLY				3

#define PAM2_HIENABLE_RW_DMI_ONLY				0
#define PAM2_HIENABLE_R_DRAM_W_DMI				1
#define PAM2_HIENABLE_R_DMI_W_DRAM				2
#define PAM2_HIENABLE_RW_DRAM_ONLY				3

#define PAM3_LOENABLE_RW_DMI_ONLY				0
#define PAM3_LOENABLE_R_DRAM_W_DMI				1
#define PAM3_LOENABLE_R_DMI_W_DRAM				2
#define PAM3_LOENABLE_RW_DRAM_ONLY				3

#define PAM3_HIENABLE_RW_DMI_ONLY				0
#define PAM3_HIENABLE_R_DRAM_W_DMI				1
#define PAM3_HIENABLE_R_DMI_W_DRAM				2
#define PAM3_HIENABLE_RW_DRAM_ONLY				3

#define PAM4_LOENABLE_RW_DMI_ONLY				0
#define PAM4_LOENABLE_R_DRAM_W_DMI				1
#define PAM4_LOENABLE_R_DMI_W_DRAM				2
#define PAM4_LOENABLE_RW_DRAM_ONLY				3

#define PAM4_HIENABLE_RW_DMI_ONLY				0
#define PAM4_HIENABLE_R_DRAM_W_DMI				1
#define PAM4_HIENABLE_R_DMI_W_DRAM				2
#define PAM4_HIENABLE_RW_DRAM_ONLY				3

#define PAM5_LOENABLE_RW_DMI_ONLY				0
#define PAM5_LOENABLE_R_DRAM_W_DMI				1
#define PAM5_LOENABLE_R_DMI_W_DRAM				2
#define PAM5_LOENABLE_RW_DRAM_ONLY				3

#define PAM5_HIENABLE_RW_DMI_ONLY				0
#define PAM5_HIENABLE_R_DRAM_W_DMI				1
#define PAM5_HIENABLE_R_DMI_W_DRAM				2
#define PAM5_HIENABLE_RW_DRAM_ONLY				3

#define PAM6_LOENABLE_RW_DMI_ONLY				0
#define PAM6_LOENABLE_R_DRAM_W_DMI				1
#define PAM6_LOENABLE_R_DMI_W_DRAM				2
#define PAM6_LOENABLE_RW_DRAM_ONLY				3

#define PAM6_HIENABLE_RW_DMI_ONLY				0
#define PAM6_HIENABLE_R_DRAM_W_DMI				1
#define PAM6_HIENABLE_R_DMI_W_DRAM				2
#define PAM6_HIENABLE_RW_DRAM_ONLY				3

#define PCH_PCI_PORT1_ASPM_DISABLED				0
#define PCH_PCI_PORT1_ASPM_L0S					1
#define PCH_PCI_PORT1_ASPM_L1_ONLY				2
#define PCH_PCI_PORT1_ASPM_L0SL1				3
#define PCH_PCI_PORT1_ASPM_AUTO					4

#define PCH_PCI_PORT2_ASPM_DISABLED				0
#define PCH_PCI_PORT2_ASPM_L0S					1
#define PCH_PCI_PORT2_ASPM_L1_ONLY				2
#define PCH_PCI_PORT2_ASPM_L0SL1				3
#define PCH_PCI_PORT2_ASPM_AUTO					4

#define PCH_PCI_PORT3_ASPM_DISABLED				0
#define PCH_PCI_PORT3_ASPM_L0S					1
#define PCH_PCI_PORT3_ASPM_L1_ONLY				2
#define PCH_PCI_PORT3_ASPM_L0SL1				3
#define PCH_PCI_PORT3_ASPM_AUTO					4

#define PCH_PCI_PORT4_ASPM_DISABLED				0
#define PCH_PCI_PORT4_ASPM_L0S					1
#define PCH_PCI_PORT4_ASPM_L1_ONLY				2
#define PCH_PCI_PORT4_ASPM_L0SL1				3
#define PCH_PCI_PORT4_ASPM_AUTO					4

#define PCH_PCI_PORT5_ASPM_DISABLED				0
#define PCH_PCI_PORT5_ASPM_L0S					1
#define PCH_PCI_PORT5_ASPM_L1_ONLY				2
#define PCH_PCI_PORT5_ASPM_L0SL1				3
#define PCH_PCI_PORT5_ASPM_AUTO					4

#define PCH_PCI_PORT6_ASPM_DISABLED				0
#define PCH_PCI_PORT6_ASPM_L0S					1
#define PCH_PCI_PORT6_ASPM_L1_ONLY				2
#define PCH_PCI_PORT6_ASPM_L0SL1				3
#define PCH_PCI_PORT6_ASPM_AUTO					4

#define PCH_PCI_PORT7_ASPM_DISABLED				0
#define PCH_PCI_PORT7_ASPM_L0S					1
#define PCH_PCI_PORT7_ASPM_L1_ONLY				2
#define PCH_PCI_PORT7_ASPM_L0SL1				3
#define PCH_PCI_PORT7_ASPM_AUTO					4

#define PCH_PCI_PORT8_ASPM_DISABLED				0
#define PCH_PCI_PORT8_ASPM_L0S					1
#define PCH_PCI_PORT8_ASPM_L1_ONLY				2
#define PCH_PCI_PORT8_ASPM_L0SL1				3
#define PCH_PCI_PORT8_ASPM_AUTO					4

#define PCIE_PORT1A_ASPM_DISABLED				0
#define PCIE_PORT1A_ASPM_L1ONLY					2
#define PCIE_PORT1A_ASPM_AUTO					7

#define PCIE_PORT1B_ASPM_DISABLED				0
#define PCIE_PORT1B_ASPM_L1ONLY					2
#define PCIE_PORT1B_ASPM_AUTO					7

#define PCIE_PORT3A_ASPM_DISABLED				0
#define PCIE_PORT3A_ASPM_L1ONLY					2
#define PCIE_PORT3A_ASPM_AUTO					7

#define PCIE_PORT3B_ASPM_DISABLED				0
#define PCIE_PORT3B_ASPM_L1ONLY					2
#define PCIE_PORT3B_ASPM_AUTO					7

#define PCIE_PORT3C_ASPM_DISABLED				0
#define PCIE_PORT3C_ASPM_L1ONLY					2
#define PCIE_PORT3C_ASPM_AUTO					7

#define PCIE_PORT3D_ASPM_DISABLED				0
#define PCIE_PORT3D_ASPM_L1ONLY					2
#define PCIE_PORT3D_ASPM_AUTO					7

#define PCH_PCI_PORT1_DISABLED					0
#define PCH_PCI_PORT1_ENABLE					1

#define PCH_PCI_PORT2_DISABLED					0
#define PCH_PCI_PORT2_ENABLE					1

#define PCH_PCI_PORT3_DISABLED					0
#define PCH_PCI_PORT3_ENABLE					1

#define PCH_PCI_PORT4_DISABLED					0
#define PCH_PCI_PORT4_ENABLE					1

#define PCH_PCI_PORT5_DISABLED					0
#define PCH_PCI_PORT5_ENABLE					1

#define PCH_PCI_PORT6_DISABLED					0
#define PCH_PCI_PORT6_ENABLE					1

#define PCH_PCI_PORT7_DISABLED					0
#define PCH_PCI_PORT7_ENABLE					1

#define PCH_PCI_PORT8_DISABLED					0
#define PCH_PCI_PORT8_ENABLE					1

#define HOTPLUG_PCH_PCI_PORT1_DISABLE			0
#define HOTPLUG_PCH_PCI_PORT1_ENABLE			1

#define HOTPLUG_PCH_PCI_PORT2_DISABLE			0
#define HOTPLUG_PCH_PCI_PORT2_ENABLE			1

#define HOTPLUG_PCH_PCI_PORT3_DISABLE			0
#define HOTPLUG_PCH_PCI_PORT3_ENABLE			1

#define HOTPLUG_PCH_PCI_PORT4_DISABLE			0
#define HOTPLUG_PCH_PCI_PORT4_ENABLE			1

#define HOTPLUG_PCH_PCI_PORT5_DISABLE			0
#define HOTPLUG_PCH_PCI_PORT5_ENABLE			1

#define HOTPLUG_PCH_PCI_PORT6_DISABLE			0
#define HOTPLUG_PCH_PCI_PORT6_ENABLE			1

#define HOTPLUG_PCH_PCI_PORT7_DISABLE			0
#define HOTPLUG_PCH_PCI_PORT7_ENABLE			1

#define HOTPLUG_PCH_PCI_PORT8_DISABLE			0
#define HOTPLUG_PCH_PCI_PORT8_ENABLE			1

#define MEM_DOWN_ENABLE_NO						0
#define MEM_DOWN_ENABLE_YES						1

#define MEM_CHANNEL_INTERLEAVE_AUTO				0
#define MEM_CHANNEL_INTERLEAVE_1WAY				1
#define MEM_CHANNEL_INTERLEAVE_2WAY				2
#define MEM_CHANNEL_INTERLEAVE_3WAY				3
#define MEM_CHANNEL_INTERLEAVE_4WAY				4

#define MEM_SCRAMBLING_DISABLED					0
#define MEM_SCRAMBLING_ENABLED					1
#define MEM_SCRAMBLING_AUTO						2

#define MEM_ECC_SUPPORT_DISABLED				0
#define MEM_ECC_SUPPORT_ENABLED					1
#define MEM_ECC_SUPPORT_AUTO					2

#define MEM_CA_PARITY_DISABLED					0
#define MEM_CA_PARITY_ENABLED					1
#define MEM_CA_PARITY_AUTO						2

#define MEM_POWER_SAVINGS_MODE_DISABLED			0
#define MEM_POWER_SAVINGS_MODE_SLOW				1
#define MEM_POWER_SAVINGS_MODE_FAST				2
#define MEM_POWER_SAVINGS_MODE_APD				3
#define MEM_POWER_SAVINGS_MODE_USER				4
#define MEM_POWER_SAVINGS_MODE_AUTO				5

#define MEM_RANK_MARGIN_TOOL_DISABLED			0
#define MEM_RANK_MARGIN_TOOL_ENABLED			1
#define MEM_RANK_MARGIN_TOOL_AUTO				2

#define MEM_RANK_MULTIPLICATION_AUTO			0
#define MEM_RANK_MULTIPLICATION_ENABLED			1

#define MEM_THERMAL_THROTTLING_DISABLED			0
#define MEM_THERMAL_THROTTLING_OPENLOOP			1
#define MEM_THERMAL_THROTTLING_CLOSEDLOOP		2

#define MEM_ELECTRICAL_THROTTLING_DISABLED		0
#define MEM_ELECTRICAL_THROTTLING_ENABLED		1
#define MEM_ELECTRICAL_THROTTLING_AUTO			2

#define MEM_FAST_BOOT_NO						0
#define MEM_FAST_BOOT_YES						1

#define MEM_DDR_MEMORY_TYPE_RDIMM_ONLY			0
#define MEM_DDR_MEMORY_TYPE_UDIMM_ONLY			1
#define MEM_DDR_MEMORY_TYPE_UDIMM_AND_RDIMM		2

#define MEM_MC0DT_OVERRIDE_50OHM				0
#define MEM_MC0DT_OVERRIDE_100OHM				1
#define MEM_MC0DT_OVERRIDE_AUTO					2

#define MEM_ADR_DISABLED						0
#define MEM_ADR_ENABLED							1
#define MEM_ADR_ENABLED_NVDIMM					2

#define MEM_RANK_INTERLEAVE_AUTO				0
#define MEM_RANK_INTERLEAVE_1WAY				1
#define MEM_RANK_INTERLEAVE_2WAY				2
#define MEM_RANK_INTERLEAVE_4WAY				4
#define MEM_RANK_INTERLEAVE_8WAY				8

#define MEM_PAGE_POLICY_OPEN					0
#define MEM_PAGE_POLICY_CLOSED					1
#define MEM_PAGE_POLICY_ADAPTIVE				2
#define MEM_PAGE_POLICY_AUTO					3

#define MEM_REFRESH_MODE_ACC_SELF_REFRESH		0
#define MEM_REFRESH_MODE_2X_REFRESH				1

#define MEM_SOCKET_INTERLEAVE_BELOW_4G_DISABLED	0
#define MEM_SOCKET_INTERLEAVE_BELOW_4G_ENABLED	1

#define MEM_BLOCKS_TRAFFIC_ON_ADR_DISABLED		0
#define MEM_BLOCKS_TRAFFIC_ON_ADR_ENABLED		1

#define CONFIG_IOU1_PCI_PORT3_X4X4X4X4			0
#define CONFIG_IOU1_PCI_PORT3_X4X4XXX8			1
#define CONFIG_IOU1_PCI_PORT3_XXX8X4X4			2
#define CONFIG_IOU1_PCI_PORT3_XXX8XXX8			3
#define CONFIG_IOU1_PCI_PORT3_XXXXXX16			4

#define CONFIG_IOU2_PCI_PORT1_X4X4				0
#define CONFIG_IOU2_PCI_PORT1_XXX8				1

#define EHCI_1ENABLE_DISABLE					0
#define EHCI_1ENABLE_ENABLE						1

#define EHCI_2ENABLE_DISABLE					0
#define EHCI_2ENABLE_ENABLE						1

#define HYPER_THREADING_DISABLE					0
#define HYPER_THREADING_ENABLE					1

#define SERIAL_PORT_CONTROLLER_INIT0_NO			0
#define SERIAL_PORT_CONTROLLER_INIT0_YES		1

#define SERIAL_PORT_CONTROLLER_INIT1_NO			0	
#define SERIAL_PORT_CONTROLLER_INIT1_YES		1	

#define SERIAL_PORT_BAUDRATE_9600				8
#define SERIAL_PORT_BAUDRATE_19200				9
#define SERIAL_PORT_BAUDRATE_38400				10
#define SERIAL_PORT_BAUDRATE_57600				11
#define SERIAL_PORT_BAUDRATE_115200				12

#define SERIAL_PORT_TYPE_NONE					0
#define SERIAL_PORT_TYPE_IO						1
#define SERIAL_PORT_TYPE_MMIO					2

#define SERIAL_PORT_CONFIGURE_NO				0
#define SERIAL_PORT_CONFIGURE_YES				1

#define BOOT_PERF_MODE_MAX_EFFICIENCY			0
#define BOOT_PERF_MODE_MAX_PERFORMANCE			1

#define TURBO_MODE_DISABLE						0
#define TURBO_MODE_ENABLE						1

#define THERMAL_DEVICE_ENABLE_DISABLED			0
#define THERMAL_DEVICE_ENABLE_ENABLED			1

#define POWER_STATE_AFTER_G3_S0					0
#define POWER_STATE_AFTER_G3_S5					1

#define DEBUG_OUTPUT_LEVEL_DISABLED				0
#define DEBUG_OUTPUT_LEVEL_MINIMUM				1
#define DEBUG_OUTPUT_LEVEL_NORMAL				2
#define DEBUG_OUTPUT_LEVEL_MAXIMUM				3

#define TCO_TIMER_HALT_LOCK_NO					0
#define TCO_TIMER_HALT_LOCK_YES					1

#define DFX_ENABLE_DISABLED						0
#define DFX_ENABLE_ENABLED						1

#endif /* __FSP_CONFIGS_H__ */
