/*
 * Copyright (C) 2017, WarOfDevil <warofdevil@linux.com>
 *
 * SPDX-License-Identifier:	GPL-2.0+
 */

#ifndef __FSP_CONFIGS_H__
#define __FSP_CONFIGS_H__

#ifndef __ASSEMBLY__
struct fsp_config_data {
	struct fsp_cfg_common	common;
	struct upd_region	fsp_upd;
};

struct fspinit_rtbuf {
	struct common_buf	common;	/* FSP common runtime data structure */
};
#endif

/* FSP user configuration settings */

#define PAM_RW_DMI_ONLY							0
#define PAM_R_DRAM_W_DMI						1
#define PAM_R_DMI_W_DRAM						2
#define PAM_RW_DRAM_ONLY						3

#define PCH_PCI_ASPM_DISABLED					0
#define PCH_PCI_ASPM_L0S						1
#define PCH_PCI_ASPM_L1_ONLY					2
#define PCH_PCI_ASPM_L0SL1						3
#define PCH_PCI_ASPM_AUTO						4

#define PCIE_ASPM_DISABLED						0
#define PCIE_ASPM_L1ONLY						2
#define PCIE_ASPM_AUTO							7

#define MEM_CHANNEL_INTERLEAVE_AUTO				0
#define MEM_CHANNEL_INTERLEAVE_1WAY				1
#define MEM_CHANNEL_INTERLEAVE_2WAY				2
#define MEM_CHANNEL_INTERLEAVE_3WAY				3
#define MEM_CHANNEL_INTERLEAVE_4WAY				4

#define MEM_SCRAMBLING_DISABLED					0
#define MEM_SCRAMBLING_ENABLED					1
#define MEM_SCRAMBLING_AUTO						2

#define MEM_ECC_SUPPORT_DISABLED				0
#define MEM_ECC_SUPPORT_ENABLED					1
#define MEM_ECC_SUPPORT_AUTO					2

#define MEM_CA_PARITY_DISABLED					0
#define MEM_CA_PARITY_ENABLED					1
#define MEM_CA_PARITY_AUTO						2

#define MEM_POWER_SAVINGS_MODE_DISABLED			0
#define MEM_POWER_SAVINGS_MODE_SLOW				1
#define MEM_POWER_SAVINGS_MODE_FAST				2
#define MEM_POWER_SAVINGS_MODE_APD				3
#define MEM_POWER_SAVINGS_MODE_USER				4
#define MEM_POWER_SAVINGS_MODE_AUTO				5

#define MEM_RANK_MARGIN_TOOL_DISABLED			0
#define MEM_RANK_MARGIN_TOOL_ENABLED			1
#define MEM_RANK_MARGIN_TOOL_AUTO				2

#define MEM_RANK_MULTIPLICATION_AUTO			0
#define MEM_RANK_MULTIPLICATION_ENABLED			1

#define MEM_THERMAL_THROTTLING_DISABLED			0
#define MEM_THERMAL_THROTTLING_OPENLOOP			1
#define MEM_THERMAL_THROTTLING_CLOSEDLOOP		2

#define MEM_ELECTRICAL_THROTTLING_DISABLED		0
#define MEM_ELECTRICAL_THROTTLING_ENABLED		1
#define MEM_ELECTRICAL_THROTTLING_AUTO			2

#define MEM_DDR_MEMORY_TYPE_RDIMM_ONLY			0
#define MEM_DDR_MEMORY_TYPE_UDIMM_ONLY			1
#define MEM_DDR_MEMORY_TYPE_UDIMM_AND_RDIMM		2

#define MEM_MC0DT_OVERRIDE_50OHM				0
#define MEM_MC0DT_OVERRIDE_100OHM				1
#define MEM_MC0DT_OVERRIDE_AUTO					2

#define MEM_ADR_DISABLED						0
#define MEM_ADR_ENABLED							1
#define MEM_ADR_ENABLED_NVDIMM					2

#define MEM_RANK_INTERLEAVE_AUTO				0
#define MEM_RANK_INTERLEAVE_1WAY				1
#define MEM_RANK_INTERLEAVE_2WAY				2
#define MEM_RANK_INTERLEAVE_4WAY				4
#define MEM_RANK_INTERLEAVE_8WAY				8

#define MEM_PAGE_POLICY_OPEN					0
#define MEM_PAGE_POLICY_CLOSED					1
#define MEM_PAGE_POLICY_ADAPTIVE				2
#define MEM_PAGE_POLICY_AUTO					3

#define MEM_REFRESH_MODE_ACC_SELF_REFRESH		0
#define MEM_REFRESH_MODE_2X_REFRESH				1

#define MEM_SOCKET_INTERLEAVE_BELOW_4G_DISABLED	0
#define MEM_SOCKET_INTERLEAVE_BELOW_4G_ENABLED	1

#define CONFIG_IOU1_PCI_PORT3_X4X4X4X4			0
#define CONFIG_IOU1_PCI_PORT3_X4X4XXX8			1
#define CONFIG_IOU1_PCI_PORT3_XXX8X4X4			2
#define CONFIG_IOU1_PCI_PORT3_XXX8XXX8			3
#define CONFIG_IOU1_PCI_PORT3_XXXXXX16			4

#define CONFIG_IOU2_PCI_PORT1_X4X4				0
#define CONFIG_IOU2_PCI_PORT1_XXX8				1

#define SERIAL_PORT_BAUDRATE_9600				8
#define SERIAL_PORT_BAUDRATE_19200				9
#define SERIAL_PORT_BAUDRATE_38400				10
#define SERIAL_PORT_BAUDRATE_57600				11
#define SERIAL_PORT_BAUDRATE_115200				12

#define SERIAL_PORT_TYPE_NONE					0
#define SERIAL_PORT_TYPE_IO						1
#define SERIAL_PORT_TYPE_MMIO					2

#define DEBUG_OUTPUT_LEVEL_DISABLED				0
#define DEBUG_OUTPUT_LEVEL_MINIMUM				1
#define DEBUG_OUTPUT_LEVEL_NORMAL				2
#define DEBUG_OUTPUT_LEVEL_MAXIMUM				3

#define MEM_FAST_BOOT_DISABLE					0
#define MEM_FAST_BOOT_ENABLE					1

#endif /* __FSP_CONFIGS_H__ */
