#
# Copyright (C) 2017, Vincenzo Bove <vincenzo.bove@prodrive-technologies.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += pci/pci.o
obj-y += cpu.o
obj-y += early_uart.o
obj-y += fsp_configs.o
obj-y += broadwell_de.o
obj-$(CONFIG_GENERATE_ACPI_TABLE) += acpi.o
